baseURL = "https://sambyte.net/systology/"
locale = "en-us"
title = "Systology"
enableGitInfo = true
taxonomies = { tag = "tags", category = "categories" }

# Useful links to learn more about tweaking code blocks:
# https://gohugo.io/configuration/markup/
# https://gohugo.io/quick-reference/syntax-highlighting-styles/
[markup]
  [markup.highlight]
    noClasses = false
    noBackground = true
    lineNos = false
    style = "modus-vivendi"

[outputs]
  home = ["HTML", "JSON", "RSS"]

[related]
  threshold = 80
  includeNewer = false
  toLower = true
  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 80
  [[related.indices]]
    name = "date"
    weight = 10
